# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/refs/heads/main/models/json/beacon-v2-default-model/cohorts/defaultSchema.json
#   timestamp: 2026-04-21T12:38:25+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class CohortType(Enum):
    study_defined = 'study-defined'
    beacon_defined = 'beacon-defined'
    user_defined = 'user-defined'


class CURIE(RootModel[constr(pattern=r'^\w[^:]+:.+$')]):
    root: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )


class FieldSchema(RootModel[str]):
    root: str = Field(
        ...,
        description='Refers to the JSON Schema which describes the set of valid attributes for this particular document type. This attribute is mostly used in schemas that should be tested in Beacon implementations.',
    )


class ApiVersion(RootModel[str]):
    root: str = Field(
        ...,
        description='Version of API, e.g. in request or response. Beacon uses a Github-style, "v"-prefixed semantic versioning format.',
        examples=['v2.0.1', 'v0.3'],
    )


class BeaconError(BaseModel):
    errorCode: int = Field(..., description='Entry not found', examples=['404'])
    errorMessage: Optional[str] = Field(
        None, examples=['The provided parameters are incomplete: `start` is missing.']
    )


class BeaconId(RootModel[str]):
    root: str = Field(
        ...,
        description='The Id of a Beacon. Usually a reversed domain string, but any URI is acceptable. The purpose of this attribute is, in the context of a Beacon network, to disambiguate responses coming from different Beacons.',
        examples=['org.example.beacon.v2', 'org.progenetix.beacon'],
    )


class CountAdjustedToItem(RootModel[Union[conint(ge=1), str]]):
    root: Union[conint(ge=1), str]


class CountAdjustedTo(RootModel[List[CountAdjustedToItem]]):
    root: List[CountAdjustedToItem] = Field(
        ...,
        description='For counts with intentional (e.g. due to privacy concerns) or technical derived imprecision this parameter offers an option to declare the range or limits for the true results. \nIf present, CountPrecision states the type of adjustment.',
        examples=[['1', '5'], ['<5']],
        max_length=2,
        min_length=1,
    )


class CountPrecision(Enum):
    exact = 'exact'
    imprecise = 'imprecise'
    rounded = 'rounded'


class Exists(RootModel[bool]):
    root: bool = Field(
        ...,
        description='Indicator of whether any record was observed in any of the collections queried. This should be non-null.',
        examples=[True],
    )


class Filters(RootModel[List[str]]):
    root: List[str] = Field(
        ...,
        description='Ontology based filters. A CURIE syntax is encouraged to be used.',
        examples=[['BTO:0000199', 'PATO:0000383']],
    )


class Granularity(Enum):
    boolean = 'boolean'
    count = 'count'
    record = 'record'


class IncludeResultsetResponses(Enum):
    ALL = 'ALL'
    HIT = 'HIT'
    MISS = 'MISS'
    NONE = 'NONE'


class Limit(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Size of the page. Use `0` to return all the results or the maximum allowed by the Beacon, if there is any.',
        examples=[10],
    )


class NonFilteredQueriesAllowed(RootModel[bool]):
    root: bool = Field(
        ...,
        description="Switch that declares if this Beacon instance, for a given entry type, admits queries that does not include any element that restrict returning all the results, like filters, parameters, ids, etc. The default value is 'true' for backward compatibility and for clarity in the request-response dialog.",
    )


class NumTotalResults(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Total number of results. NOT the number of results returned in this batch (after pagination) but the total obtained by the query.',
        examples=[123],
    )


class PageToken(RootModel[str]):
    root: str = Field(
        ...,
        description='A hash or similar that allows the server to retrieve a "page", e.g. (a subset of) a query response.',
        examples=['ab0sc&fe1dd'],
    )


class SchemasPerEntity(BaseModel):
    entityType: Optional[str] = Field(None, examples=['Individual'])
    schema_: Optional[str] = Field(
        None,
        alias='schema',
        examples=[
            './ga4gh-beacon-dataset-v2.0.0',
            'https://www.example.org/schemas/ga4gh-beacon-dataset-v2.0.0.json',
        ],
    )


class Skip(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='* In the request: number of pages to skip * In the response: number of pages that has been skipped',
        examples=[0],
    )


class TestMode(RootModel[bool]):
    root: bool = Field(
        ...,
        description='Used for indicating that a request or response is done in a test context e.g. for compliance testing i.e. to evaluate the acceptance/understanding of a request and the structure of the returned response by the Beacon instance. A TRUE `testMode` parameter DOES NOT require that the Beacon instance is a test instance, but that this specific request-response cycle is a testing one. When `true` the Beacon instance MUST respond the request but it SHOULD use virtual or non-sensitive data. Here, what is being evaluated is the acceptance/understanding of a request and the structure of the returned response by the Beacon instance.',
    )


class Info(BaseModel):
    pass


class Age(BaseModel):
    iso8601duration: str = Field(
        ...,
        description='Represents age as a ISO8601 duration (e.g., P40Y10M05D).',
        examples=['P32Y6M1D'],
    )


class GestationalAge(BaseModel):
    days: Optional[int] = Field(
        None,
        description='Days beyond the completed weeks, if available.',
        examples=[2, 4],
    )
    weeks: int = Field(
        ...,
        description='Completed weeks of gestation according to the above definition.',
        examples=[4, 33],
    )


class Timestamp(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(
        ...,
        description='Time in date-time ISO8601 string format.',
        examples=['1999-08-05T17:21:00+01:00', '2002-09-21T02:37:00-08:00'],
    )


class CountAdjustedTo1(RootModel[List[CountAdjustedToItem]]):
    root: List[CountAdjustedToItem] = Field(
        ...,
        description='For counts with intentional (e.g. due to privacy concerns) or technical derived imprecision this parameter offers an option to declare the range or limits for the true results. \nIf present, CountPrecision states the type of adjustment.',
        examples=[['1', '5'], ['<5']],
        max_length=2,
        min_length=1,
    )


class KaryotypicSex(Enum):
    UNKNOWN_KARYOTYPE = 'UNKNOWN_KARYOTYPE'
    XX = 'XX'
    XY = 'XY'
    XO = 'XO'
    XXY = 'XXY'
    XXX = 'XXX'
    XXYY = 'XXYY'
    XXXY = 'XXXY'
    XXXX = 'XXXX'
    XYY = 'XYY'
    OTHER_KARYOTYPE = 'OTHER_KARYOTYPE'


class TimeInterval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    end: Timestamp = Field(..., examples=['2022-03-10T15:25:07Z'])
    start: Timestamp = Field(
        ..., examples=['1999-08-05T17:21:00+01:00', '2002-09-21T02:37:00-08:00']
    )


class ExternalReference(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: Optional[str] = Field(
        None,
        description='An application specific identifier. RECOMMENDED.',
        examples=['PMID:34054918'],
    )
    notes: Optional[str] = Field(
        None,
        description='An optional text descriptor. Renamed compared to GA4GH Phenopackets v2 `ExternalReference.description`',
        examples=[
            'Signatures of Discriminative Copy Number Aberrations in 31 Cancer Subtypes'
        ],
    )
    reference: Optional[str] = Field(
        None,
        description='A url.',
        examples=['https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8155688/'],
    )


class EventTimeline(BaseModel):
    end: Optional[AwareDatetime] = Field(
        None,
        description='Latest date of visit or collection timeline',
        examples=[
            '2018-10-01T13:23:45Z',
            '2019-04-23T09:11:13Z',
            '2017-01-17T20:33:40Z',
        ],
    )
    start: Optional[AwareDatetime] = Field(
        None,
        description='Earliest date of visit or collection timeline',
        examples=[
            '2018-10-01T13:23:45Z',
            '2019-04-23T09:11:13Z',
            '2017-01-17T20:33:40Z',
        ],
    )


class DataAvailabilityAndDistribution(BaseModel):
    availability: bool = Field(..., description='data availability')
    availabilityCount: Optional[int] = Field(
        None, description='Count of individuals with data available'
    )
    distribution: Optional[Dict[str, Dict[str, Any]]] = Field(
        None,
        description='List of categories and results or counts for each category.',
        examples=[{'genders': {'female': 51, 'male': 50}}],
    )


class OntologyTerm(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: CURIE
    label: Optional[str] = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class HandoverType(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Handover type, as an Ontology_term object with CURIE syntax for the `id` value. Use "CUSTOM:123455" CURIE-style `id` when no ontology is available.',
        examples=[
            {'id': 'EDAM:2572', 'label': 'BAM'},
            {'id': 'EDAM:3016', 'label': 'VCF'},
            {'id': 'CUSTOM:pgxseg', 'label': 'genomic variants in .pgxseg file format'},
        ],
    )


class ListOfSchemas(RootModel[List[SchemasPerEntity]]):
    root: List[SchemasPerEntity] = Field(
        ..., description='Set of schemas to be used in the response to a request.'
    )


class Pagination(BaseModel):
    currentPage: Optional[PageToken] = Field(
        None,
        description='Token of the returned page. To be used only in the response to allow the client to check if the returned page is the one requested.',
    )
    limit: Optional[Limit] = Field(default_factory=lambda: Limit.model_validate(10))
    nextPage: Optional[PageToken] = Field(
        None,
        description='Token of the next page. Used to navigate forward. If empty, it is assumed that no more pages are available',
    )
    previousPage: Optional[PageToken] = Field(
        None,
        description='Token of the previous page. Used to navigate backwards. If empty, it is assumed that the current page is the first one.',
    )
    skip: Optional[Skip] = 0


class AgeRange(BaseModel):
    end: Age = Field(
        ..., description='Represents age as an ISO8601 duration (e.g., P59Y).'
    )
    start: Age = Field(
        ..., description='Represents age as an ISO8601 duration (e.g., P18Y).'
    )


class TimeElement(
    RootModel[
        Union[Age, AgeRange, GestationalAge, Timestamp, TimeInterval, OntologyTerm]
    ]
):
    root: Union[
        Age, AgeRange, GestationalAge, Timestamp, TimeInterval, OntologyTerm
    ] = Field(
        ...,
        description='Definition of a wrapper for various time descriptors. This follows the\nPhenopackets structure https://github.com/phenopackets/phenopacket-schema/blob/v2/docs/time-element.rst',
        title='TimeElement',
    )


class Pagination1(BaseModel):
    currentPage: Optional[PageToken] = Field(
        None,
        description='Token of the returned page. To be used only in the response to allow the client to check if the returned page is the one requested.',
    )
    limit: Optional[Limit] = Field(default_factory=lambda: Limit.model_validate(10))
    nextPage: Optional[PageToken] = Field(
        None,
        description='Token of the next page. Used to navigate forward. If empty, it is assumed that no more pages are available',
    )
    previousPage: Optional[PageToken] = Field(
        None,
        description='Token of the previous page. Used to navigate backwards. If empty, it is assumed that the current page is the first one.',
    )
    skip: Optional[Skip] = 0


class GeographicLocation(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Country or region of origin of the individual (birthplace or residence place regardless of ethnic origin). Value from GAZ Geographic Location ontology (GAZ:00000448), e.g. GAZ:00002459 (United States of America).',
        examples=[
            {'id': 'GAZ:00002955', 'label': 'Slovenia'},
            {'id': 'GAZ:00002459', 'label': 'United States of America'},
            {'id': 'GAZ:00316959', 'label': 'Municipality of El Masnou'},
            {'id': 'GAZ:00000460', 'label': 'Eurasia'},
        ],
    )


class SeverityLevel(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Severity as applicable to phenotype or disease observed. Recommended are values from Human Phenotype Ontology (HP:0012824), e.g `mild`. The intensity or degree of a manifestation. Source: Phenopackets v2',
        examples=[
            {'id': 'HP:0012828', 'label': 'Severe'},
            {'id': 'HP:0012829', 'label': 'Profound'},
            {'id': 'HP:0012826', 'label': 'Moderate'},
            {'id': 'HP:0012825', 'label': 'Mild'},
            {'id': 'HP:0012827', 'label': 'Borderline'},
        ],
    )


class Sex(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Sex of the individual. Recommended values from NCIT General Qualifier (NCIT:C27993): "unknown" (not assessed or not available) - NCIT:C17998; "female" - NCIT:C16576;  "male" - NCIT:C20197',
        examples=[
            {'id': 'NCIT:C16576', 'label': 'female'},
            {'id': 'NCIT:C20197', 'label': 'male'},
            {'id': 'NCIT:C1799', 'label': 'unknown'},
        ],
    )


class Unit(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='The kind of unit. Recommended from NCIT Unit of Category ontology term (NCIT:C42568) descendants',
        examples=[
            {'id': 'NCIT:C70575', 'label': 'Roentgen'},
            {'id': 'NCIT:C28252', 'label': 'Kilogram'},
            {'id': 'NCIT:C28253', 'label': 'Milligram'},
        ],
    )


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    evidenceCode: OntologyTerm = Field(
        ...,
        description='An ontology class that represents the evidence type',
        examples=[
            {
                'id': 'ECO:0006017',
                'label': 'author statement from published clinical study used in manual assertion',
            }
        ],
    )
    reference: Optional[ExternalReference] = Field(
        None,
        description='Representation of the source of the evidence',
        examples=[
            {
                'id': 'PMID:30962759',
                'label': 'Recurrent Erythema Nodosum in a Child with a SHOC2 Gene Mutation',
            }
        ],
    )


class CollectionEvent(BaseModel):
    eventAgeRange: Optional[DataAvailabilityAndDistribution] = Field(
        None,
        description='Individual age range, obtained from individual level info of the cohort members',
    )
    eventCases: Optional[int] = Field(
        None, description='number of cases', examples=[543, 20]
    )
    eventControls: Optional[int] = Field(
        None, description='number of controls', examples=[1000, 22]
    )
    eventDataTypes: Optional[DataAvailabilityAndDistribution] = Field(
        None,
        description='Aggregated data type information available for each cohort data type as declared in `cohortDataTypes`, and obtained from individual level info of the cohort members',
    )
    eventDate: Optional[AwareDatetime] = Field(
        None,
        description='date of collection event/data point',
        examples=[
            '2018-10-01T13:23:45Z',
            '2019-04-23T09:11:13Z',
            '2017-01-17T20:33:40Z',
        ],
    )
    eventDiseases: Optional[DataAvailabilityAndDistribution] = Field(
        None,
        description='Aggregated information of disease/condition(s) obtained from individual level info of the cohort members',
    )
    eventEthnicities: Optional[DataAvailabilityAndDistribution] = Field(
        None,
        description='Aggregated information of ethnicity obtained from individual level info of the cohort members',
    )
    eventGenders: Optional[DataAvailabilityAndDistribution] = Field(
        None,
        description='Aggregated information of gender(s) obtained from individual level info of the cohort members',
    )
    eventLocations: Optional[DataAvailabilityAndDistribution] = Field(
        None,
        description='Aggregated information of geographic location obtained from individual level info of the cohort members',
    )
    eventNum: Optional[int] = Field(
        None,
        description='cardinality of the collection event / data point in a series',
        examples=[1, 2, 3, 4],
    )
    eventPhenotypes: Optional[DataAvailabilityAndDistribution] = Field(
        None,
        description='Aggregated information of phenotype(s) obtained from individual level info of the cohort members',
    )
    eventSize: Optional[int] = Field(
        None,
        description='Count of individuals in cohort at data point (for ´user-defined´ cohorts, this is individuals meeting criteria) obtained from individual level info in database.',
        examples=[1543, 42],
    )
    eventTimeline: Optional[EventTimeline] = Field(
        None,
        description='Aggregated information of dates of visit | diagnostic | inclusion in study obtained from individual level info of the cohort members.',
    )


class DataTypesArray(RootModel[List[OntologyTerm]]):
    root: List[OntologyTerm] = Field(
        ...,
        description='Type of information. Preferably values from Genomics Cohorts Knowledge Ontology (GeCKO) or others when GeCKO is not applicable.',
        examples=[
            {'id': 'OGMS:0000015', 'label': 'clinical history'},
            {'id': 'OBI:0000070', 'label': 'genotyping assay'},
            {'id': 'OMIABIS:0000060', 'label': 'survey data'},
        ],
    )


class Handover(BaseModel):
    handoverType: HandoverType
    note: Optional[str] = Field(
        None,
        description='An optional text including considerations on the handover link provided.',
        examples=['This handover link provides access to a summarized VCF.'],
    )
    url: AnyUrl = Field(
        ...,
        description='URL endpoint to where the handover process could progress, in RFC3986 format',
        examples=[
            'https://api.mygenomeservice.org/Handover/9dcc48d7-fc88-11e8-9110-b0c592dbf8c0/'
        ],
    )


class ListOfHandovers(RootModel[List[Handover]]):
    root: List[Handover] = Field(
        ..., description='Set of handovers to be added in one section the response.'
    )


class Disease(BaseModel):
    ageOfOnset: Optional[TimeElement] = Field(
        None,
        examples=[
            {'id': 'NCIT:C49685', 'label': 'Adult 18-65 Years Old'},
            {'iso8601duration': 'P32Y6M1D'},
            {'end': {'iso8601duration': 'P59Y'}, 'start': {'iso8601duration': 'P18Y'}},
            {'iso8601duration': 'P2M4D'},
        ],
    )
    diseaseCode: OntologyTerm = Field(
        ...,
        description='Disease identifier. Value from disease ontologies such as HPO, OMIM, Orphanet, MONDO, e.g. lactose intolerance (HP:0004789, ICD10CM:E73). Provenance: GA4GH Phenopackets v2 `Disease.term`',
        examples=[
            {'id': 'HP:0004789', 'label': 'lactose intolerance'},
            {'id': 'ICD10CM:E73', 'label': 'lactose intolerance'},
            {'id': 'OMIM:164400', 'label': 'Spinocerebellar ataxia 1'},
        ],
    )
    familyHistory: Optional[bool] = Field(
        None,
        description='Boolean indicating determined or self-reported presence of family history of the disease.',
        examples=[True],
    )
    notes: Optional[str] = Field(
        None,
        description='Unstructured text to describe additional properties of this disease instance.',
        examples=['Some free text'],
    )
    severity: Optional[SeverityLevel] = Field(
        None,
        examples=[
            {'id': 'HP:0012828', 'label': 'Severe'},
            {'id': 'HP:0012826', 'label': 'Moderate'},
        ],
    )
    stage: Optional[OntologyTerm] = Field(
        None,
        description='Ontology term from Ontology for General Medical Science (OGMS), e.g. acute onset (OGMS:0000119). Provenance: GA4GH Phenopackets v2 `Disease.disease_stage`',
        examples=[
            {'id': 'OGMS:0000119', 'label': 'acute onset'},
            {'id': 'OGMS:0000117', 'label': 'asymptomatic'},
            {'id': 'OGMS:0000106', 'label': 'remission'},
        ],
    )


class Ethnicity(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Ethnic background of the individual. Recommended is the use of a value from NCIT Race (NCIT:C17049) ontology term descendants, e.g. NCIT:C126531 (Latin American). A geographic ancestral origin category that is assigned to a population group based mainly on physical characteristics that are thought to be distinct and inherent. [ NCI ]',
        examples=[
            {'id': 'NCIT:C42331', 'label': 'African'},
            {'id': 'NCIT:C41260', 'label': 'Asian'},
            {'id': 'NCIT:C126535', 'label': 'Australian'},
            {'id': 'NCIT:C43851', 'label': 'European'},
            {'id': 'NCIT:C77812', 'label': 'North American'},
            {'id': 'NCIT:C126531', 'label': 'Latin American'},
            {'id': 'NCIT:C104495', 'label': 'Other race'},
        ],
    )


class ListOfHandovers1(RootModel[List[Handover]]):
    root: List[Handover] = Field(
        ..., description='Set of handovers to be added in one section the response.'
    )


class PhenotypicFeature(BaseModel):
    evidence: Optional[Evidence] = Field(
        None,
        description='The evidence for an assertion of the observation of a type. RECOMMENDED.',
    )
    excluded: Optional[bool] = Field(
        False,
        description='Flag to indicate whether the phenotypic feature was observed or not. Default is ‘false’, in other words the phenotype was observed. Therefore it is only used in cases where the phenotype was looked for but found to be absent. More formally, this modifier indicates the logical negation of the OntologyClass used in the `featureType` field. CAUTION: It is imperative to check this field for correct interpretation of the phenotype! Source: Phenopackets v2',
    )
    featureType: OntologyTerm = Field(
        ...,
        description='Term denoting the phenotypic feature, preferably using a value from Human Phenotype Ontology (HPO)',
        examples=[
            {'id': 'HP:0000002', 'label': 'Abnormality of body height'},
            {'id': 'HP:0002006', 'label': 'Facial cleft'},
            {'id': 'HP:0012469', 'label': 'Infantile spasms'},
        ],
    )
    modifiers: Optional[List[OntologyTerm]] = Field(
        None,
        description='This subontology is designed to provide terms to characterize and specify the phenotypic abnormalities defined in the Phenotypic abnormality subontology, with respect to severity, laterality, age of onset, and other aspects. Example use here would be one or more terms from HPO Clinical Modifier (HP:0012823). Source: Phenopackets v2',
        examples=[
            {'id': 'HP:0032500', 'label': 'Exacerbated by tobacco use'},
            {'id': 'HP:4000053', 'label': 'Displaced fracture'},
        ],
    )
    notes: Optional[str] = Field(
        None,
        description='Unstructured text to describe additional properties of this phenotypic feature.',
        examples=['Some free text'],
    )
    onset: Optional[TimeElement] = Field(
        None, description='Age or time at which the feature was first observed.'
    )
    resolution: Optional[TimeElement] = Field(
        None, description='Age or time at which the feature resolved or abated.'
    )
    severity: Optional[SeverityLevel] = Field(
        None,
        examples=[
            {'id': 'HP:0012828', 'label': 'Severe'},
            {'id': 'HP:0012826', 'label': 'Moderate'},
        ],
    )


class CohortCriteria(BaseModel):
    ageRange: Optional[AgeRange] = Field(
        None, description='Individual age range in cohort inclusion criteria'
    )
    diseaseConditions: Optional[List[Disease]] = Field(
        None, description='Diseases in cohort inclusion criteria'
    )
    ethnicities: Optional[List[Ethnicity]] = Field(
        None, description='Ethnias in cohort inclusion criteria'
    )
    genders: Optional[List[Sex]] = Field(
        None, description='Gender(s) in cohort inclusion criteria'
    )
    locations: Optional[List[GeographicLocation]] = Field(
        None, description='Geographic location(s) in cohort inclusion criteria'
    )
    phenotypicConditions: Optional[List[PhenotypicFeature]] = Field(
        None, description='Phenotypic condition(s) in cohort inclusion criteria'
    )


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    cohortDataTypes: Optional[DataTypesArray] = None
    cohortDesign: Optional[OntologyTerm] = Field(
        None,
        description='Cohort type by its design. A plan specification comprised of protocols (which may specify how and what kinds of data will be gathered) that are executed as part of an investigation and is realized during a study design execution. Value from Ontologized MIABIS (OMIABIS) Study design ontology term tree (OBI:0500000).',
        examples=[
            {'id': 'OMIABIS:0001017', 'label': 'case control study design'},
            {'id': 'OMIABIS:0001019', 'label': 'longitudinal study design'},
            {'id': 'OMIABIS:0001024', 'label': 'twin study design'},
        ],
    )
    cohortSize: Optional[int] = Field(
        None,
        description='Count of unique Individuals in cohort (individuals meeting criteria for `user-defined` cohorts). If not previously known, it could be calculated by counting the individuals in the cohort.',
        examples=[14765, 20000],
    )
    cohortType: CohortType = Field(
        ...,
        description='Cohort type by its definition. If a cohort is declared `study-defined` or `beacon-defined` criteria are to be entered `in cohort_inclusion_criteria`; if a cohort is declared `user-defined` `cohort_inclusion_criteria` could be automatically populated from the parameters used to perform the query.',
    )
    collectionEvents: Optional[List[CollectionEvent]] = Field(None, description='TBD')
    exclusionCriteria: Optional[CohortCriteria] = Field(
        None,
        description='Exclusion criteria used for defining the cohort. It is assumed that NONE of the cohort participants will match such criteria.',
    )
    id: str = Field(
        ...,
        description='Cohort identifier. For `study-defined` or `beacon-defined` cohorts this field is set by the implementer. For `user-defined` this unique identifier could be generated upon the query that defined the cohort, but could be later edited by the user.',
        examples=['cohort-T2D-2010'],
    )
    inclusionCriteria: Optional[CohortCriteria] = Field(
        None,
        description='Inclusion criteria used for defining the cohort. It is assumed that all cohort participants will match such criteria.',
    )
    info: Optional[Info] = None
    name: str = Field(
        ...,
        description='Name of the cohort. For `user-defined` this field could be generated upon the query, e.g. a value that is a concatenationor some representation of the user query.',
        examples=['Wellcome Trust Case Control Consortium', 'GCAT Genomes for Life'],
    )
