# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/refs/heads/main/models/json/beacon-v2-default-model/genomicVariations/endpoints.json
#   timestamp: 2026-04-21T11:43:23+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Schema(BaseModel):
    type: str


class AlternateBases(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema = Field(..., alias='schema')


class AminoacidChange(BaseModel):
    example: str
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema = Field(..., alias='schema')


class AssemblyId(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema = Field(..., alias='schema')


class Items(BaseModel):
    format: str
    minimum: int
    type: str


class Schema3(BaseModel):
    items: Items
    maxItems: int
    minItems: int
    type: str


class End(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema3 = Field(..., alias='schema')


class Schema4(BaseModel):
    type: str


class EntryId(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    required: bool
    schema_: Schema4 = Field(..., alias='schema')


class Example1(BaseModel):
    value: List[str]


class Example2(BaseModel):
    value: List[str]


class Example3(BaseModel):
    value: List[str]


class Examples(BaseModel):
    example1: Example1
    example2: Example2
    example3: Example3


class Items1(BaseModel):
    type: str


class Schema5(BaseModel):
    items: Items1
    type: str


class Filters(BaseModel):
    examples: Examples
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema5 = Field(..., alias='schema')


class Schema6(BaseModel):
    type: str


class GeneId(BaseModel):
    example: str
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema6 = Field(..., alias='schema')


class GenomicAlleleShortForm(BaseModel):
    example: str
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema6 = Field(..., alias='schema')


class Schema8(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class IncludeResultsetResponses(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema8 = Field(..., alias='schema')


class Limit(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema8 = Field(..., alias='schema')


class Schema10(BaseModel):
    type: str


class ReferenceBases(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema10 = Field(..., alias='schema')


class ReferenceName(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema10 = Field(..., alias='schema')


class RequestedSchema(BaseModel):
    description: str
    example: str
    in_: str = Field(..., alias='in')
    name: str
    required: bool
    schema_: Schema10 = Field(..., alias='schema')


class Schema13(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Skip(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema13 = Field(..., alias='schema')


class Items2(BaseModel):
    format: str
    minimum: int
    type: str


class Schema14(BaseModel):
    items: Items2
    maxItems: int
    minItems: int
    type: str


class Start(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema14 = Field(..., alias='schema')


class Schema15(BaseModel):
    format: str
    minimum: int
    type: str


class VariantMaxLength(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema15 = Field(..., alias='schema')


class VariantMinLength(BaseModel):
    in_: str = Field(..., alias='in')
    name: str
    schema_: Schema15 = Field(..., alias='schema')


class Parameters(BaseModel):
    alternateBases: AlternateBases
    aminoacidChange: AminoacidChange
    assemblyId: AssemblyId
    end: End
    entryId: EntryId
    filters: Filters
    geneId: GeneId
    genomicAlleleShortForm: GenomicAlleleShortForm
    includeResultsetResponses: IncludeResultsetResponses
    limit: Limit
    referenceBases: ReferenceBases
    referenceName: ReferenceName
    requestedSchema: RequestedSchema
    skip: Skip
    start: Start
    variantMaxLength: VariantMaxLength
    variantMinLength: VariantMinLength


class OneOfItem(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Schema17(BaseModel):
    oneOf: List[OneOfItem]


class ApplicationJson(BaseModel):
    schema_: Schema17 = Field(..., alias='schema')


class Content(BaseModel):
    application_json: ApplicationJson = Field(..., alias='application/json')


class ResultsOKResponse(BaseModel):
    content: Content
    description: str


class Responses(BaseModel):
    ResultsOKResponse_1: ResultsOKResponse = Field(..., alias='ResultsOKResponse')


class Components(BaseModel):
    parameters: Parameters
    responses: Responses


class Contact(BaseModel):
    email: str


class License(BaseModel):
    name: str
    url: str


class Info(BaseModel):
    contact: Contact
    description: str
    license: License
    title: str
    version: str


class Parameter(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Field200(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Default(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Responses1(BaseModel):
    field_200: Field200 = Field(..., alias='200')
    default: Default


class Get(BaseModel):
    description: str
    operationId: str
    parameters: List[Parameter]
    responses: Responses1
    tags: List[str]


class Schema18(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class ApplicationJson1(BaseModel):
    schema_: Schema18 = Field(..., alias='schema')


class Content1(BaseModel):
    application_json: ApplicationJson1 = Field(..., alias='application/json')


class RequestBody(BaseModel):
    content: Content1
    required: bool


class ApplicationJson2(BaseModel):
    schema_: Schema18 = Field(..., alias='schema')


class Content2(BaseModel):
    application_json: ApplicationJson2 = Field(..., alias='application/json')


class Default1(BaseModel):
    content: Content2
    description: str


class Responses2(BaseModel):
    field_200: Field200 = Field(..., alias='200')
    default: Default1


class Post(BaseModel):
    description: str
    operationId: str
    requestBody: RequestBody
    responses: Responses2
    tags: List[str]


class FieldGVariants(BaseModel):
    get: Get
    post: Post


class ApplicationJson3(BaseModel):
    schema_: Schema18 = Field(..., alias='schema')


class Content3(BaseModel):
    application_json: ApplicationJson3 = Field(..., alias='application/json')


class Default2(BaseModel):
    content: Content3
    description: str


class Responses3(BaseModel):
    field_200: Field200 = Field(..., alias='200')
    default: Default2


class Get1(BaseModel):
    description: str
    operationId: str
    responses: Responses3
    tags: List[str]


class ApplicationJson4(BaseModel):
    schema_: Schema18 = Field(..., alias='schema')


class Content4(BaseModel):
    application_json: ApplicationJson4 = Field(..., alias='application/json')


class RequestBody1(BaseModel):
    content: Content4
    required: bool


class ApplicationJson5(BaseModel):
    schema_: Schema18 = Field(..., alias='schema')


class Content5(BaseModel):
    application_json: ApplicationJson5 = Field(..., alias='application/json')


class Default3(BaseModel):
    content: Content5
    description: str


class Responses4(BaseModel):
    field_200: Field200 = Field(..., alias='200')
    default: Default3


class Post1(BaseModel):
    description: str
    operationId: str
    requestBody: RequestBody1
    responses: Responses4
    tags: List[str]


class FieldGVariantsId(BaseModel):
    get: Get1
    parameters: List[Parameter]
    post: Post1


class ApplicationJson6(BaseModel):
    schema_: Schema18 = Field(..., alias='schema')


class Content6(BaseModel):
    application_json: ApplicationJson6 = Field(..., alias='application/json')


class Default4(BaseModel):
    content: Content6
    description: str


class Responses5(BaseModel):
    field_200: Field200 = Field(..., alias='200')
    default: Default4


class Get2(BaseModel):
    description: str
    operationId: str
    parameters: List[Parameter]
    responses: Responses5
    tags: List[str]


class ApplicationJson7(BaseModel):
    schema_: Schema18 = Field(..., alias='schema')


class Content7(BaseModel):
    application_json: ApplicationJson7 = Field(..., alias='application/json')


class RequestBody2(BaseModel):
    content: Content7
    required: bool


class ApplicationJson8(BaseModel):
    schema_: Schema18 = Field(..., alias='schema')


class Content8(BaseModel):
    application_json: ApplicationJson8 = Field(..., alias='application/json')


class Default5(BaseModel):
    content: Content8
    description: str


class Responses6(BaseModel):
    field_200: Field200 = Field(..., alias='200')
    default: Default5


class Post2(BaseModel):
    description: str
    operationId: str
    requestBody: RequestBody2
    responses: Responses6
    tags: List[str]


class FieldGVariantsIdBiosamples(BaseModel):
    get: Get2
    parameters: List[Parameter]
    post: Post2


class ApplicationJson9(BaseModel):
    schema_: Schema18 = Field(..., alias='schema')


class Content9(BaseModel):
    application_json: ApplicationJson9 = Field(..., alias='application/json')


class Default6(BaseModel):
    content: Content9
    description: str


class Responses7(BaseModel):
    field_200: Field200 = Field(..., alias='200')
    default: Default6


class Get3(BaseModel):
    description: str
    operationId: str
    parameters: List[Parameter]
    responses: Responses7
    tags: List[str]


class ApplicationJson10(BaseModel):
    schema_: Schema18 = Field(..., alias='schema')


class Content10(BaseModel):
    application_json: ApplicationJson10 = Field(..., alias='application/json')


class RequestBody3(BaseModel):
    content: Content10
    required: bool


class ApplicationJson11(BaseModel):
    schema_: Schema18 = Field(..., alias='schema')


class Content11(BaseModel):
    application_json: ApplicationJson11 = Field(..., alias='application/json')


class Default7(BaseModel):
    content: Content11
    description: str


class Responses8(BaseModel):
    field_200: Field200 = Field(..., alias='200')
    default: Default7


class Post3(BaseModel):
    description: str
    operationId: str
    requestBody: RequestBody3
    responses: Responses8
    tags: List[str]


class FieldGVariantsIdIndividuals(BaseModel):
    get: Get3
    parameters: List[Parameter]
    post: Post3


class Paths(BaseModel):
    field_g_variants: FieldGVariants = Field(..., alias='/g_variants')
    field_g_variants__id_: FieldGVariantsId = Field(..., alias='/g_variants/{id}')
    field_g_variants__id__biosamples: FieldGVariantsIdBiosamples = Field(
        ..., alias='/g_variants/{id}/biosamples'
    )
    field_g_variants__id__individuals: FieldGVariantsIdIndividuals = Field(
        ..., alias='/g_variants/{id}/individuals'
    )


class Model(BaseModel):
    components: Components
    info: Info
    openapi: str
    paths: Paths
    servers: List
