# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/refs/heads/main/framework/json/responses/beaconFilteringTermsResponse.json
#   timestamp: 2026-04-21T12:22:52+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, conint, constr


class ApiVersion(RootModel[str]):
    root: str = Field(
        ...,
        description='Version of API, e.g. in request or response. Beacon uses a Github-style, "v"-prefixed semantic versioning format.',
        examples=['v2.0.1', 'v0.3'],
    )


class FieldSchema(RootModel[str]):
    root: str = Field(
        ...,
        description='Refers to the JSON Schema which describes the set of valid attributes for this particular document type. This attribute is mostly used in schemas that should be tested in Beacon implementations.',
    )


class BeaconError(BaseModel):
    errorCode: int = Field(..., description='Entry not found', examples=['404'])
    errorMessage: Optional[str] = Field(
        None, examples=['The provided parameters are incomplete: `start` is missing.']
    )


class BeaconId(RootModel[str]):
    root: str = Field(
        ...,
        description='The Id of a Beacon. Usually a reversed domain string, but any URI is acceptable. The purpose of this attribute is, in the context of a Beacon network, to disambiguate responses coming from different Beacons.',
        examples=['org.example.beacon.v2', 'org.progenetix.beacon'],
    )


class CURIE(RootModel[constr(pattern=r'^\w[^:]+:.+$')]):
    root: constr(pattern=r'^\w[^:]+:.+$') = Field(
        ...,
        description='Definition of an identifier in the CURIE `prefix:local-part` format which is the default type of e.g. ontology term `id` values (used e.g. for filters or external identifiers).',
        examples=[
            'ga4gh:GA.01234abcde',
            'DUO:0000004',
            'orcid:0000-0003-3463-0775',
            'PMID:15254584',
        ],
    )


class CountAdjustedToItem(RootModel[Union[conint(ge=1), str]]):
    root: Union[conint(ge=1), str]


class CountAdjustedTo(RootModel[List[CountAdjustedToItem]]):
    root: List[CountAdjustedToItem] = Field(
        ...,
        description='For counts with intentional (e.g. due to privacy concerns) or technical derived imprecision this parameter offers an option to declare the range or limits for the true results. \nIf present, CountPrecision states the type of adjustment.',
        examples=[['1', '5'], ['<5']],
        max_length=2,
        min_length=1,
    )


class CountPrecision(Enum):
    exact = 'exact'
    imprecise = 'imprecise'
    rounded = 'rounded'


class Exists(RootModel[bool]):
    root: bool = Field(
        ...,
        description='Indicator of whether any record was observed in any of the collections queried. This should be non-null.',
        examples=[True],
    )


class Filters(RootModel[List[str]]):
    root: List[str] = Field(
        ...,
        description='Ontology based filters. A CURIE syntax is encouraged to be used.',
        examples=[['BTO:0000199', 'PATO:0000383']],
    )


class Granularity(Enum):
    boolean = 'boolean'
    count = 'count'
    record = 'record'


class OntologyTerm(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: CURIE
    label: Optional[str] = Field(
        None,
        description='The text that describes the term. By default it could be the preferred text of the term, but is it acceptable to customize it for a clearer description and understanding of the term in an specific context.',
    )


class IncludeResultsetResponses(Enum):
    ALL = 'ALL'
    HIT = 'HIT'
    MISS = 'MISS'
    NONE = 'NONE'


class Limit(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Size of the page. Use `0` to return all the results or the maximum allowed by the Beacon, if there is any.',
        examples=[10],
    )


class NonFilteredQueriesAllowed(RootModel[bool]):
    root: bool = Field(
        ...,
        description="Switch that declares if this Beacon instance, for a given entry type, admits queries that does not include any element that restrict returning all the results, like filters, parameters, ids, etc. The default value is 'true' for backward compatibility and for clarity in the request-response dialog.",
    )


class NumTotalResults(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Total number of results. NOT the number of results returned in this batch (after pagination) but the total obtained by the query.',
        examples=[123],
    )


class PageToken(RootModel[str]):
    root: str = Field(
        ...,
        description='A hash or similar that allows the server to retrieve a "page", e.g. (a subset of) a query response.',
        examples=['ab0sc&fe1dd'],
    )


class SchemasPerEntity(BaseModel):
    entityType: Optional[str] = Field(None, examples=['Individual'])
    schema_: Optional[str] = Field(
        None,
        alias='schema',
        examples=[
            './ga4gh-beacon-dataset-v2.0.0',
            'https://www.example.org/schemas/ga4gh-beacon-dataset-v2.0.0.json',
        ],
    )


class Skip(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='* In the request: number of pages to skip * In the response: number of pages that has been skipped',
        examples=[0],
    )


class TestMode(RootModel[bool]):
    root: bool = Field(
        ...,
        description='Used for indicating that a request or response is done in a test context e.g. for compliance testing i.e. to evaluate the acceptance/understanding of a request and the structure of the returned response by the Beacon instance. A TRUE `testMode` parameter DOES NOT require that the Beacon instance is a test instance, but that this specific request-response cycle is a testing one. When `true` the Beacon instance MUST respond the request but it SHOULD use virtual or non-sensitive data. Here, what is being evaluated is the acceptance/understanding of a request and the structure of the returned response by the Beacon instance.',
    )


class FilteringTermInResponse(BaseModel):
    id: str = Field(
        ...,
        description='The field id in the case of numeric or alphanumeric fields, or the term id in the case of ontology or custom terms. CURIE syntax in the case of an ontology term.',
        examples=['NCIT:C8936', 'HP:0008773'],
    )
    label: Optional[str] = Field(
        None,
        description='This would be the "preferred Label" in the case of an ontology term.',
        examples=[
            'B Lymphoblastic Leukemia/Lymphoma',
            'Aplasia/Hypoplasia of the middle ear',
        ],
    )
    scopes: Optional[List[str]] = Field(
        None,
        description='Entry types affected by this filter.',
        examples=[
            ['individual', 'biosample', 'analysis', 'run', 'genomicVariation'],
            ['biosample'],
        ],
    )
    type: str = Field(
        ...,
        description='Either "custom", "alphanumeric" or ontology/terminology full name. TODO: An ontology ... with a registered prefix does not need a full name so one may better use CURIE to indicate that the resource can be retrieved from the id. This also will allow to provide an enum here.',
        examples=['Human Phenotype Ontology', 'alphanumeric'],
    )
    values: Optional[List[str]] = Field(
        None,
        description='Optional list of possible values for alphanumeric filters',
        examples=[['benign', 'likely benign', 'pathogenic'], ['pathogenic']],
        min_length=1,
    )


class Resource(BaseModel):
    id: str = Field(
        ...,
        description='Preferably OBO ID representing the resource; alternatively a URI pointing towards the definitions may be used if not in OBO.',
        examples=['hp'],
    )
    iriPrefix: Optional[str] = Field(
        None,
        description='The full Internationalized Resource Identifier (IRI) prefix',
        examples=['https://purl.obolibrary.org/obo/HP_'],
    )
    name: Optional[str] = Field(
        None,
        description='The name of the ontology referred to by the id element',
        examples=['Human Phenotype Ontology'],
    )
    nameSpacePrefix: Optional[str] = Field(
        None,
        description='The prefix used in the CURIE of an OntologyClass',
        examples=['HP'],
    )
    url: Optional[str] = Field(
        None,
        description='Uniform Resource Locator of the resource',
        examples=['https://purl.obolibrary.org/obo/hp.owl'],
    )
    version: Optional[str] = Field(
        None,
        description='The version of the resource or ontology used to make the annotation',
        examples=['17-06-2019'],
    )


class HandoverType(RootModel[OntologyTerm]):
    root: OntologyTerm = Field(
        ...,
        description='Handover type, as an Ontology_term object with CURIE syntax for the `id` value. Use "CUSTOM:123455" CURIE-style `id` when no ontology is available.',
        examples=[
            {'id': 'EDAM:2572', 'label': 'BAM'},
            {'id': 'EDAM:3016', 'label': 'VCF'},
            {'id': 'CUSTOM:pgxseg', 'label': 'genomic variants in .pgxseg file format'},
        ],
    )


class ListOfSchemas(RootModel[List[SchemasPerEntity]]):
    root: List[SchemasPerEntity] = Field(
        ..., description='Set of schemas to be used in the response to a request.'
    )


class Pagination(BaseModel):
    currentPage: Optional[PageToken] = Field(
        None,
        description='Token of the returned page. To be used only in the response to allow the client to check if the returned page is the one requested.',
    )
    limit: Optional[Limit] = Field(default_factory=lambda: Limit.model_validate(10))
    nextPage: Optional[PageToken] = Field(
        None,
        description='Token of the next page. Used to navigate forward. If empty, it is assumed that no more pages are available',
    )
    previousPage: Optional[PageToken] = Field(
        None,
        description='Token of the previous page. Used to navigate backwards. If empty, it is assumed that the current page is the first one.',
    )
    skip: Optional[Skip] = 0


class BeaconFilteringTermsResults(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    filteringTerms: Optional[List[FilteringTermInResponse]] = None
    resources: Optional[List[Resource]] = None


class BeaconInformationalResponseMeta(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    apiVersion: ApiVersion
    beaconId: BeaconId
    returnedSchemas: ListOfSchemas


class Handover(BaseModel):
    handoverType: HandoverType
    note: Optional[str] = Field(
        None,
        description='An optional text including considerations on the handover link provided.',
        examples=['This handover link provides access to a summarized VCF.'],
    )
    url: AnyUrl = Field(
        ...,
        description='URL endpoint to where the handover process could progress, in RFC3986 format',
        examples=[
            'https://api.mygenomeservice.org/Handover/9dcc48d7-fc88-11e8-9110-b0c592dbf8c0/'
        ],
    )


class ListOfHandovers(RootModel[List[Handover]]):
    root: List[Handover] = Field(
        ..., description='Set of handovers to be added in one section the response.'
    )


class Model(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    meta: BeaconInformationalResponseMeta
    response: BeaconFilteringTermsResults
