# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/refs/heads/main/framework/json/responses/ga4gh-service-info-1-0-0-schema.json
#   timestamp: 2026-04-21T11:43:24+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class Organization(BaseModel):
    name: str = Field(
        ...,
        description='Name of the organization responsible for the service',
        examples=['My organization'],
    )
    url: AnyUrl = Field(
        ...,
        description='URL of the website of the organization (RFC 3986 format)',
        examples=['https://example.com'],
    )


class ServiceType(BaseModel):
    artifact: str = Field(
        ...,
        description='Name of the API or GA4GH specification implemented. Official GA4GH types should be assigned as part of standards approval process. Custom artifacts are supported.',
        examples=['beacon'],
    )
    group: str = Field(
        ...,
        description="Namespace in reverse domain name format. Use `org.ga4gh` for implementations compliant with official GA4GH specifications. For services with custom APIs not standardized by GA4GH, or implementations diverging from official GA4GH specifications, use a different namespace (e.g. your organization's reverse domain name).",
        examples=['org.ga4gh'],
    )
    version: str = Field(
        ...,
        description='Version of the API or specification. GA4GH specifications use semantic versioning.',
        examples=['1.0.0'],
    )


class Ga4GhServiceInfoApiSpecification(BaseModel):
    contactUrl: Optional[AnyUrl] = Field(
        None,
        description='URL of the contact for the provider of this service, e.g. a link to a contact form (RFC 3986 format), or an email (RFC 2368 format).',
        examples=['mailto:support@example.com'],
    )
    createdAt: Optional[AwareDatetime] = Field(
        None,
        description='Timestamp describing when the service was first deployed and available (RFC 3339 format)',
        examples=['2019-06-04T12:58:19Z'],
    )
    description: Optional[str] = Field(
        None,
        description='Description of the service. Should be human readable and provide information about the service.',
        examples=['This service provides...'],
    )
    documentationUrl: Optional[AnyUrl] = Field(
        None,
        description='URL of the documentation of this service (RFC 3986 format). This should help someone learn how to use your service, including any specifics required to access data, e.g. authentication.',
        examples=['https://docs.myservice.example.com'],
    )
    environment: Optional[str] = Field(
        None,
        description='Environment the service is running in. Use this to distinguish between production, development and testing/staging deployments. Suggested values are prod, test, dev, staging. However this is advised and not enforced.',
        examples=['test'],
    )
    id: str = Field(
        ...,
        description='Unique ID of this service. Reverse domain name notation is recommended, though not required. The identifier should attempt to be globally unique so it can be used in downstream aggregator services e.g. Service Registry.',
        examples=['org.ga4gh.myservice'],
    )
    name: str = Field(
        ...,
        description='Name of this service. Should be human readable.',
        examples=['My project'],
    )
    organization: Organization = Field(
        ..., description='Organization providing the service'
    )
    type: ServiceType
    updatedAt: Optional[AwareDatetime] = Field(
        None,
        description='Timestamp describing when the service was last updated (RFC 3339 format)',
        examples=['2019-06-04T12:58:19Z'],
    )
    version: str = Field(
        ...,
        description='Version of the service being described. Semantic versioning is recommended, but other identifiers, such as dates or commit hashes, are also allowed. The version should be changed whenever the service is updated.',
        examples=['1.0.0'],
    )
